// Code generated by gen/main.go.

package q1_devirt

// M00 has 0 statement(s); used to locate the inliner budget boundary.
func (c *C1) M00(x int64) int64 {
	return x
}

// M01 has 1 statement(s); used to locate the inliner budget boundary.
func (c *C1) M01(x int64) int64 {
	x = x*2 + int64(1)
	return x
}

// M02 has 2 statement(s); used to locate the inliner budget boundary.
func (c *C1) M02(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	return x
}

// M03 has 3 statement(s); used to locate the inliner budget boundary.
func (c *C1) M03(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	return x
}

// M04 has 4 statement(s); used to locate the inliner budget boundary.
func (c *C1) M04(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	return x
}

// M05 has 5 statement(s); used to locate the inliner budget boundary.
func (c *C1) M05(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	return x
}

// M06 has 6 statement(s); used to locate the inliner budget boundary.
func (c *C1) M06(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	return x
}

// M07 has 7 statement(s); used to locate the inliner budget boundary.
func (c *C1) M07(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	return x
}

// M08 has 8 statement(s); used to locate the inliner budget boundary.
func (c *C1) M08(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	return x
}

// M09 has 9 statement(s); used to locate the inliner budget boundary.
func (c *C1) M09(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	return x
}

// M10 has 10 statement(s); used to locate the inliner budget boundary.
func (c *C1) M10(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	return x
}

// M11 has 11 statement(s); used to locate the inliner budget boundary.
func (c *C1) M11(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	return x
}

// M12 has 12 statement(s); used to locate the inliner budget boundary.
func (c *C1) M12(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	return x
}

// M13 has 13 statement(s); used to locate the inliner budget boundary.
func (c *C1) M13(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	return x
}

// M14 has 14 statement(s); used to locate the inliner budget boundary.
func (c *C1) M14(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	return x
}

// M15 has 15 statement(s); used to locate the inliner budget boundary.
func (c *C1) M15(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	return x
}

// M16 has 16 statement(s); used to locate the inliner budget boundary.
func (c *C1) M16(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	return x
}

// M17 has 17 statement(s); used to locate the inliner budget boundary.
func (c *C1) M17(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	return x
}

// M18 has 18 statement(s); used to locate the inliner budget boundary.
func (c *C1) M18(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	return x
}

// M19 has 19 statement(s); used to locate the inliner budget boundary.
func (c *C1) M19(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	return x
}

// M20 has 20 statement(s); used to locate the inliner budget boundary.
func (c *C1) M20(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	return x
}

// M21 has 21 statement(s); used to locate the inliner budget boundary.
func (c *C1) M21(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	return x
}

// M22 has 22 statement(s); used to locate the inliner budget boundary.
func (c *C1) M22(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	return x
}

// M23 has 23 statement(s); used to locate the inliner budget boundary.
func (c *C1) M23(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	return x
}

// M24 has 24 statement(s); used to locate the inliner budget boundary.
func (c *C1) M24(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	return x
}

// M25 has 25 statement(s); used to locate the inliner budget boundary.
func (c *C1) M25(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	return x
}

// M26 has 26 statement(s); used to locate the inliner budget boundary.
func (c *C1) M26(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	return x
}

// M27 has 27 statement(s); used to locate the inliner budget boundary.
func (c *C1) M27(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	return x
}

// M28 has 28 statement(s); used to locate the inliner budget boundary.
func (c *C1) M28(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	x = x*2 + int64(28)
	return x
}

// M29 has 29 statement(s); used to locate the inliner budget boundary.
func (c *C1) M29(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	x = x*2 + int64(28)
	x = x*2 + int64(29)
	return x
}

// M30 has 30 statement(s); used to locate the inliner budget boundary.
func (c *C1) M30(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	x = x*2 + int64(28)
	x = x*2 + int64(29)
	x = x*2 + int64(30)
	return x
}

// M31 has 31 statement(s); used to locate the inliner budget boundary.
func (c *C1) M31(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	x = x*2 + int64(28)
	x = x*2 + int64(29)
	x = x*2 + int64(30)
	x = x*2 + int64(31)
	return x
}

// M32 has 32 statement(s); used to locate the inliner budget boundary.
func (c *C1) M32(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	x = x*2 + int64(28)
	x = x*2 + int64(29)
	x = x*2 + int64(30)
	x = x*2 + int64(31)
	x = x*2 + int64(32)
	return x
}

// M33 has 33 statement(s); used to locate the inliner budget boundary.
func (c *C1) M33(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	x = x*2 + int64(28)
	x = x*2 + int64(29)
	x = x*2 + int64(30)
	x = x*2 + int64(31)
	x = x*2 + int64(32)
	x = x*2 + int64(33)
	return x
}

// M34 has 34 statement(s); used to locate the inliner budget boundary.
func (c *C1) M34(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	x = x*2 + int64(28)
	x = x*2 + int64(29)
	x = x*2 + int64(30)
	x = x*2 + int64(31)
	x = x*2 + int64(32)
	x = x*2 + int64(33)
	x = x*2 + int64(34)
	return x
}

// M35 has 35 statement(s); used to locate the inliner budget boundary.
func (c *C1) M35(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	x = x*2 + int64(28)
	x = x*2 + int64(29)
	x = x*2 + int64(30)
	x = x*2 + int64(31)
	x = x*2 + int64(32)
	x = x*2 + int64(33)
	x = x*2 + int64(34)
	x = x*2 + int64(35)
	return x
}

// M36 has 36 statement(s); used to locate the inliner budget boundary.
func (c *C1) M36(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	x = x*2 + int64(28)
	x = x*2 + int64(29)
	x = x*2 + int64(30)
	x = x*2 + int64(31)
	x = x*2 + int64(32)
	x = x*2 + int64(33)
	x = x*2 + int64(34)
	x = x*2 + int64(35)
	x = x*2 + int64(36)
	return x
}

// M37 has 37 statement(s); used to locate the inliner budget boundary.
func (c *C1) M37(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	x = x*2 + int64(28)
	x = x*2 + int64(29)
	x = x*2 + int64(30)
	x = x*2 + int64(31)
	x = x*2 + int64(32)
	x = x*2 + int64(33)
	x = x*2 + int64(34)
	x = x*2 + int64(35)
	x = x*2 + int64(36)
	x = x*2 + int64(37)
	return x
}

// M38 has 38 statement(s); used to locate the inliner budget boundary.
func (c *C1) M38(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	x = x*2 + int64(28)
	x = x*2 + int64(29)
	x = x*2 + int64(30)
	x = x*2 + int64(31)
	x = x*2 + int64(32)
	x = x*2 + int64(33)
	x = x*2 + int64(34)
	x = x*2 + int64(35)
	x = x*2 + int64(36)
	x = x*2 + int64(37)
	x = x*2 + int64(38)
	return x
}

// M39 has 39 statement(s); used to locate the inliner budget boundary.
func (c *C1) M39(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	x = x*2 + int64(28)
	x = x*2 + int64(29)
	x = x*2 + int64(30)
	x = x*2 + int64(31)
	x = x*2 + int64(32)
	x = x*2 + int64(33)
	x = x*2 + int64(34)
	x = x*2 + int64(35)
	x = x*2 + int64(36)
	x = x*2 + int64(37)
	x = x*2 + int64(38)
	x = x*2 + int64(39)
	return x
}

// M40 has 40 statement(s); used to locate the inliner budget boundary.
func (c *C1) M40(x int64) int64 {
	x = x*2 + int64(1)
	x = x*2 + int64(2)
	x = x*2 + int64(3)
	x = x*2 + int64(4)
	x = x*2 + int64(5)
	x = x*2 + int64(6)
	x = x*2 + int64(7)
	x = x*2 + int64(8)
	x = x*2 + int64(9)
	x = x*2 + int64(10)
	x = x*2 + int64(11)
	x = x*2 + int64(12)
	x = x*2 + int64(13)
	x = x*2 + int64(14)
	x = x*2 + int64(15)
	x = x*2 + int64(16)
	x = x*2 + int64(17)
	x = x*2 + int64(18)
	x = x*2 + int64(19)
	x = x*2 + int64(20)
	x = x*2 + int64(21)
	x = x*2 + int64(22)
	x = x*2 + int64(23)
	x = x*2 + int64(24)
	x = x*2 + int64(25)
	x = x*2 + int64(26)
	x = x*2 + int64(27)
	x = x*2 + int64(28)
	x = x*2 + int64(29)
	x = x*2 + int64(30)
	x = x*2 + int64(31)
	x = x*2 + int64(32)
	x = x*2 + int64(33)
	x = x*2 + int64(34)
	x = x*2 + int64(35)
	x = x*2 + int64(36)
	x = x*2 + int64(37)
	x = x*2 + int64(38)
	x = x*2 + int64(39)
	x = x*2 + int64(40)
	return x
}

