// Package emitter translates javac-produced class files into Go source
// (P-0006 / ADR-0003 source-emission path). Generated files carry a DO NOT
// EDIT header (architecture-rules R6) and follow emitter-abi.md.
package emitter

import (
	"fmt"
	"sort"
	"strings"

	"catty/internal/classfile"
)

const generatedHeader = "// Code generated by catty-genemit v2; DO NOT EDIT.\n\npackage gen\n"

// EmitProgram emits every class into one Go file. A single file keeps
// registration order and cross-class references trivial for v1.
func EmitProgram(files ...*classfile.ClassFile) (string, error) {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("import (\n\t\"catty/internal/genrt\"\n\t\"catty/internal/kernel\"\n)\n\n")

	// Registration table consumed by Install at boot.
	b.WriteString("// installTable maps emitted methods onto kernel method entries.\n")
	b.WriteString("var installTable []struct {\n\tcls, name, desc string\n\tfn              func(kernel.OwnerKey, kernel.Value, []kernel.Value) (kernel.Value, *kernel.Thrown)\n}\n")

	for _, cf := range files {
		if err := emitClass(&b, cf); err != nil {
			return "", err
		}
	}

	// Install overrides interpreted bodies for emitted methods. Idempotent
	// per method; classes that load LATER (nested classes, library deps —
	// they resolve lazily at first `new`) are covered by the kernel's
	// class-load hook.
	b.WriteString(`// Install wires emitted bodies into the kernel (call once after loading).
func Install(k *kernel.Kernel) {
	genrt.InstallKernel(k)
	apply := func(c *kernel.Class) {
		for _, e := range installTable {
			if e.cls != c.Name {
				continue // class not in this run
			}
			m, err := k.ResolveMethod(c, e.name, e.desc)
			if err != nil {
				panic("gen install: " + err.Error())
			}
			if m.EmitBody != nil {
				continue // already installed (repeat loads / idempotence)
			}
			f := e.fn
			m.EmitBody = func(th kernel.OwnerKey, recv kernel.Value, args []kernel.Value) (kernel.Value, *kernel.Thrown) {
				return f(th, recv, args)
			}
			m.Native = func(ctx *kernel.CallContext, recv kernel.Value, args []kernel.Value) (kernel.Value, error) {
				v, exc := f(ctx.Owner, recv, args)
				if exc != nil {
					return nil, exc
				}
				return v, nil
			}
		}
	}
	for _, e := range installTable {
		if c, ok := k.ClassByName(e.cls); ok {
			apply(c)
		}
	}
	k.SetClassLoadHook(apply)
}`)

	return b.String(), nil
}

func emitClass(b *strings.Builder, cf *classfile.ClassFile) error {
	for i := range cf.Methods {
		m := &cf.Methods[i]
		if m.Code == nil || m.Name == "<clinit>" {
			continue // clinit runs through the interpreter's init machinery
		}
		fnName := MethodFunc(cf.ThisClass, m.Name, m.Desc)
		body, err := emitMethodBody(cf, m)
		if err != nil {
			return fmt.Errorf("%s.%s%s: %w", cf.ThisClass, m.Name, m.Desc, err)
		}
		fmt.Fprintf(b, "\n// %s.%s\n", cf.ThisClass, m.Name)
		fmt.Fprintf(b, "func %s(thr kernel.OwnerKey, recv kernel.Value, args []kernel.Value) (kernel.Value, *kernel.Thrown) {\n%s}\n",
			fnName, body)
		fmt.Fprintf(b, "func init() { installTable = append(installTable,\n\tstruct{ cls, name, desc string; fn func(kernel.OwnerKey, kernel.Value, []kernel.Value) (kernel.Value, *kernel.Thrown) }{%q, %q, %q, %s}) }\n",
			cf.ThisClass, m.Name, m.Desc, fnName)
	}
	return nil
}

// sortedStringConstants extracts unique string literals from the pool.
func sortedStringConstants(cf *classfile.ClassFile) map[uint16]string {
	out := make(map[uint16]string)
	for i := range cf.Constants {
		e := &cf.Constants[i]
		if e.Tag == classfile.CString {
			if s, err := cf.UTF8(e.Idx1); err == nil {
				out[uint16(i)] = s
			}
		}
	}
	return out
}

func sortKeys(m map[uint16]string) []uint16 {
	keys := make([]uint16, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(a, b int) bool { return keys[a] < keys[b] })
	return keys
}
